// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlGaIXR9AL_Cn2X7sQNDOxvw0p1bZeBuI',
    appId: '1:364280515228:web:956f7b23cf801d6382bb59',
    messagingSenderId: '364280515228',
    projectId: 'esp32-6efca',
    authDomain: 'esp32-6efca.firebaseapp.com',
    databaseURL: 'https://esp32-6efca-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-6efca.appspot.com',
    measurementId: 'G-4RJRK04P1X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDANXyyc1sGtyIWVfuwGBYcKoQuikdxsEM',
    appId: '1:364280515228:android:757ec907b4cfbb8882bb59',
    messagingSenderId: '364280515228',
    projectId: 'esp32-6efca',
    databaseURL: 'https://esp32-6efca-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-6efca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4uB1ktqjkqwNx6nIgoN3j9XC6I43tYc',
    appId: '1:364280515228:ios:ab47dc355d3bdacf82bb59',
    messagingSenderId: '364280515228',
    projectId: 'esp32-6efca',
    databaseURL: 'https://esp32-6efca-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-6efca.appspot.com',
    iosBundleId: 'com.example.liquidDispenser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4uB1ktqjkqwNx6nIgoN3j9XC6I43tYc',
    appId: '1:364280515228:ios:ab47dc355d3bdacf82bb59',
    messagingSenderId: '364280515228',
    projectId: 'esp32-6efca',
    databaseURL: 'https://esp32-6efca-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-6efca.appspot.com',
    iosBundleId: 'com.example.liquidDispenser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlGaIXR9AL_Cn2X7sQNDOxvw0p1bZeBuI',
    appId: '1:364280515228:web:6c7ac22f35717abc82bb59',
    messagingSenderId: '364280515228',
    projectId: 'esp32-6efca',
    authDomain: 'esp32-6efca.firebaseapp.com',
    databaseURL: 'https://esp32-6efca-default-rtdb.firebaseio.com',
    storageBucket: 'esp32-6efca.appspot.com',
    measurementId: 'G-FMNC73Q2WV',
  );
}
